basic:
  name: æˆ´ç»´è¥
  designation: iOSè½¯ä»¶å·¥ç¨‹å¸ˆ
  age: 25
  gender: ç”·
  email: Cowbye@foxmail.com
  phone: +86 73189606715
  website: http://v.diveinedu.com
online_handles:
  weibo: Cowbye
  github: Cowbye
  weixin: Cowbye
self_evaluation:
  contents:
    - ä¸€ä¸ªèªæ˜ï¼Œæ•é”ï¼Œå¼€æ”¾ï¼Œå¯Œæœ‰æ¿€æƒ…çš„ç§»åŠ¨äº’è”ç½‘å¼€å‘è€…ã€‚
    - ä¸€ä¸ªå‹‡æ•¢ï¼Œæ— ç•ï¼Œæ­£ä¹‰ï¼Œæ‰€å‘æŠ«é¡çš„æˆ´ç»´è¥é€€å½¹çš„æˆ˜å£«ã€‚
skills:
  - title: Programming
    contents:
      - C/Objective-C/C++
      - HTML/HTML5/CSS
      - Javascript
      - Swift
      - Design Pattern
  - title: 'Frameworks & Technologies'
    contents:
      - Cocoa Touch
      - Core Data
      - Storyboard/AutoLayout
      - ReactiveCocoa
      - PhoneGap
work_experience:
  - company: æ¹–å—æ­¥æ­¥é«˜ç”µå­å•†åŠ¡æœ‰é™è´£ä»»å…¬å¸
    time_span: 2014/01 - 2015/06
    designation: iOSç ”å‘å·¥ç¨‹å¸ˆ
    website: http://www.bbg.com.cn
    summary: ç»´æŠ¤è€é¡¹ç›®ï¼Œå¼€å‘æ–°é¡¹ç›®ï¼›å¯¹äº§å“è¿›è¡Œè¿­ä»£å¼€å‘ã€‚
    responsibilities:
      - äº†è§£åŸæœ‰é¡¹ç›®æ¶æ„å’Œä¸šåŠ¡é€»è¾‘
      - ä»£ç ç»´æŠ¤ä»¥åŠå¼€å‘æ–°éœ€æ±‚å’Œæ–°é¡¹ç›®
      - å’Œå›¢é˜Ÿè¿›è¡Œæµ‹è¯•é©±åŠ¨å¼€å‘å’Œç»“å¯¹ç¼–ç¨‹ ğŸ˜Š
projects:
  - name: äº‘çŒ´å…¨çƒè´­
    role: Developer
    time_span: 2015/04 - 2015/06
    website: http://www.yunhou.com
    summary: äº‘çŒ´å…¨çƒè´­æ˜¯ä¸€æ¬¾è´­ä¹°æµ·å¤–å•†å“çš„ç”µå•†Appï¼Œæ‹¥æœ‰å„å¤§å“ç‰Œçš„åŒ–å¦†å“å’Œå®¶ç”µç­‰ã€‚
    bullet_points:
      - ä½¿ç”¨SDKå®ç°ç¬¬ä¸‰æ–¹çš„åˆ†äº«
      - é›†æˆæ”¯ä»˜å®SDKå®ç°ç§»åŠ¨å®‰å…¨æ”¯ä»˜
      - é‡‡ç”¨ç³»ç»ŸAPIå®ç°äºŒç»´ç æ‰«æåŠŸèƒ½
      - ä½¿ç”¨SDWebImageåšå¼‚æ­¥åŠ è½½å’Œç¼“å­˜å›¾ç‰‡

  - name: è¥å†…èŠ
    role: Developer 
    time_span: 2014/08 - 2014/10
    website: https://github.com/Diveinedu-CN/PeiniYunSDK
    summary: è¥å†…èŠæ˜¯ä¸€æ¬¾åŸºäºXMPPåè®®çš„IMç¤¾äº¤è½¯ä»¶ï¼Œç”¨äºå‘˜å·¥ä¹‹é—´çš„ä¿¡æ¯äº¤æµå’Œå·¥ä½œæ²Ÿé€šã€‚
    bullet_points:
      - ç”¨Storyboard/AutoLayoutå¿«é€Ÿæ­å»ºæ‰€æœ‰çš„UIç•Œé¢
      - ä½¿ç”¨XMPPFrameworkå’Œåå°Openfireé€šä¿¡å®ç°IMåŠŸèƒ½
      - æ·»åŠ XMPPFrameworkçš„XEP0096æ‰©å±•å®ç°ByteStreamsæ–‡ä»¶ä¼ è¾“
      - ä½¿ç”¨KeyChainå¼€æºæ¡†æ¶å¯¹è´¦æˆ·ç­‰æ•æ„Ÿä¿¡æ¯è¿›è¡ŒåŠ å¯†å­˜å‚¨
      - ä½¿ç”¨DVIRefreshæ¡†æ¶å®ç°ä¸Šä¸‹æ‹‰åŠ è½½åˆ·æ–°ä¿¡æ¯
      - é‡‡ç”¨WebRTCå®ç°å®æ—¶çš„éŸ³è§†é¢‘é€šè¯åŠŸèƒ½
      - é‡‡ç”¨WebSocketåšä¿¡ä»¤åè®®æ¥å»ºç«‹é€šè¯

education:
  - institution: æ¹–å—å¤§å­¦ï¼Œé•¿æ²™
    course: è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯ï¼æœ¬ç§‘
    time_span: 2010/09 - 2014/06

interests:
  - ç§»åŠ¨å¼€å‘
  - 'é˜…è¯» & å†™ä½œ'
  - ç”µå½±